name: Test

on:
  schedule:
    - cron: "0 7 * * 0"
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:

  check:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        deno-version:
          - v1.x
    runs-on: ${{ matrix.runner }}
    steps:

      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - uses: actions/cache@v4
        with:
          key: deno-${{ runner.os }}-${{ hashFiles('deno.lock', '.github/workflows/**') }}
          restore-keys: deno-${{ runner.os }}-
          path: ~/.cache/deno

      - name: Check
        run: deno task check

  test-deno:
    needs: check
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        deno-version:
          - v1.x
    runs-on: ${{ matrix.runner }}
    steps:

      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - uses: actions/cache@v4
        with:
          key: deno-${{ runner.os }}-${{ hashFiles('deno.lock', '.github/workflows/**') }}
          restore-keys: deno-${{ runner.os }}-
          path: ~/.cache/deno

      - name: Check
        run: deno task check

      - name: Test
        run: deno task test:coverage

      - name: Coverage
        run: deno task coverage --lcov --output=./lcov

      - uses: codecov/codecov-action@v4
        with:
          files: ./lcov
          token: ${{ secrets.CODECOV_TOKEN }}

  test-node:
    needs: check
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        node-version:
          - 18
          - 20
          - 22
    runs-on: ${{ matrix.runner }}
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Setup
        run: npm ci

      - name: Test
        run: npm run test
